Reddit/config/routes.rb
Rails.application.routes.draw do
  
  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
  
  resources :subs do 
    resources :posts, only: [:create]
  end 
  resources :posts, only: [:destroy, :edit, :update]
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Reddit/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Reddit/app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :bigint(8)        not null, primary key
#  url        :string           not null
#  title      :string           not null
#  content    :text
#  sub_id     :integer          not null
#  user_id    :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Post < ApplicationRecord 
  
  validates :title, presence: true 
  
  belongs_to :author,
    foreign_key: :user_id,
    class_name: :User 
    
  belongs_to :sub 
  
  has_many :post_subs,
    foreign_key: :post_id,
    class_name: 'PostSub'
  
  has_many :sub_posts,
    through: :post_subs,
    source: :sub
  
end

Reddit/app/models/post_sub.rb
class PostSub < ApplicationRecord
  
  belongs_to :post
  belongs_to :sub
  
end

Reddit/app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id          :bigint(8)        not null, primary key
#  title       :string           not null
#  user_id     :integer          not null
#  description :text             not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Sub < ApplicationRecord 
  validates :title, :description, presence: true 
  
  has_many :posts,
  foreign_key: :sub_id,
  class_name: :Post 
  
  belongs_to :user 
  
  has_many :post_subs,
    foreign_key: :sub_id,
    class_name: 'PostSub'
  
end

Reddit/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint(8)        not null, primary key
#  username        :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord 
  
  validates :username, :password_digest, presence: true 
  
  validates :password, length: {minimum: 6, allow_nil: true }
  
  attr_reader :password 
  
  has_many :subs
  
  has_many :posts
  
  after_initialize :ensure_session_token 
  
  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    user && user.is_password?(password) ? user : nil 
  end
  
  def is_password?(pw)
    BCrypt::Password.new(self.password_digest).is_password?(pw)
  end
  
  def password=(pw)
    @password = pw 
    self.password_digest = BCrypt::Password.create(pw)
  
  end
  
  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64
  end
  
  def reset_session_token! 
    self.session_token = SecureRandom.urlsafe_base64
    self.save!
    self.session_token
  end
  
end

Reddit/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  helper_method :current_user, :logged_in?
  
  def current_user 
    @current_user ||= User.find_by_session_token(session[:session_token])
  end
  
  def login(user)
    session[:session_token] = user.reset_session_token!
    @current_user = user 
  end
  
  def require_login! 
    redirect_to new_session_url unless logged_in? 
  end
  
  def logged_in? 
    !!current_user
  end
  
  def logout 
    current_user.reset_session_token! 
    session[:session_token] = nil 
  end
end

Reddit/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  before_action :require_login!
  
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    @post.sub_id = params[:sub_id]
    
    if @post.save
      redirect_to sub_url(@post.sub_id)
    else
      flash[:errors] = @post.errors.full_messages
      redirect_to sub_url(@post.sub_id)
    end
  end
  
  def edit
    @post = Post.find(params[:id])
  end
  
  def update
    @post = current_user.posts.find(params[:id])
    
    if @post.update_attributes(post_params)
      redirect_to sub_url(@post.sub_id)
    else
      flash[:errors] = @post.errors.full_messages
      redirect_to sub_url(@post.sub_id)
    end
  end
  
  
  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to sub_url(@post.sub_id)
  end
  
  private
  
  def post_params
    params.require(:post).permit(:title, :content)
  end
end

Reddit/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
    
  end
  
  def create 
    @user = User.find_by_credentials(params[:user][:username], params[:user][:password])
    if @user 
      login(@user)
      redirect_to subs_url
    else 
      flash.now[:errors] = ["Invalid Login Info"]
      render :new 
    end 
  end
  
  def destroy 
    logout 
    redirect_to new_session_url 
  end
end

Reddit/app/controllers/subs_controller.rb
class SubsController < ApplicationController
  
  before_action :require_login!
  
  def new
    @sub = Sub.new
  end

  def create
    @sub = Sub.new(sub_params)               
    @sub.user_id = current_user.id
    
    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :show 
    end
  end

  def index
    @subs = Sub.all
  end

  def show
    @sub = Sub.find(params[:id])
  end  

  def update
    @sub = current_user.subs.find(params[:id])
    
    if @sub.update_attributes(sub_params)
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :show 
    end
  end

  def edit
    @sub = Sub.find(params[:id])
  end
  
  private
  
  def sub_params
    params.require(:sub).permit(:title, :description)
  end
  
end

Reddit/app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new 
    @user = User.new 
  end
  
  def create
    @user = User.new(user_params)
    if @user.save 
      login(@user)
      redirect_to subs_url 
    else 
      flash.now[:errors] = @user.errors.full_messages 
      render :new 
    end 
  end
  
  private 
  def user_params 
    params.require(:user).permit(:username, :password)
  end
end

Reddit/app/helpers/application_helper.rb
module ApplicationHelper
end

Reddit/app/helpers/posts_helper.rb
module PostsHelper
end

Reddit/app/helpers/sessions_helper.rb
module SessionsHelper
end

Reddit/app/helpers/subs_helper.rb
module SubsHelper
end

Reddit/app/helpers/users_helper.rb
module UsersHelper
end

Reddit/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reddit</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <% if logged_in? %>
      <%= current_user.username %>
      <form action="<%= session_url %>" method="post">
        
        <input type="hidden" name="authenticity_token" 
        value="form_authenticity_token">
        <input type="hidden" name="_method" value="delete">
        
        <input type="submit" name="" value="Sign Out">
      </form>
    <% else %>
      <a href="<%= new_user_url %>">Sign Up</a>
    <% end %>
    
    <% if flash[:errors] %>
      <% flash[:errors].each do |err| %>
        <li><%= err %></li>
      <% end %>
    <% end %>
    
    <%= yield %>
  </body>
</html>

Reddit/app/views/subs/edit.html.erb
<h1>Edit Sub</h1>

Reddit/app/views/subs/index.html.erb
<h1>All Subs</h1>

<% @subs.each do |sub| %>
  <li><a href="<%=sub_url(sub)%>"><%=sub.title%></a></li>
<% end %>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

<a href="<%= new_sub_url %>">Create New Sub</a>

Reddit/app/views/subs/new.html.erb
<h1>New Sub</h1>


<form action="<%= subs_url %>" method="post">
  <input type="hidden" name="authenticity_token" 
  value="<%= form_authenticity_token%>">
  
  <label>Title
    <input type="text" name="sub[title]" value="">
  </label>
  
  <label>Description
    <input type="text" name="sub[description]" value="">
  </label>
  
  <input type="submit" name="" value="Create Sub">
  
</form>

Reddit/app/views/subs/show.html.erb
<h1>Show Sub</h1>

<%= @sub.title %>
<%= @sub.description %>

<% @sub.posts.each do |post| %>
  <li><%= post.title %>: <%= post.content %></li>
<% end %>

<h1>Add Post</h1>

<form action="<%= sub_posts_url(@sub) %>" method="post">
  <input type="hidden" name="authenticity_token" 
  value="form_authenticity_token">
  
  
  <label>Title
    <input type="text" name="post[title]" value="">
  </label>
  
  <label>Content
    <input type="text" name="post[content]" value="">
  </label>
  

  
  <input type="submit" name="" value="Add Post">
</form>

<a href="<%= subs_url %>">All Subs</a>

Reddit/app/views/users/new.html.erb
<h1>Sign Up</h1>

<form action="<%= users_url %>" method="post">
  <input type="hidden" name="authenticity_token" 
  value="<%= form_authenticity_token%>">
  
  <label>Username
    <input type="text" name="user[username]" value="">
  </label>
  
  <label>Password
    <input type="text" name="user[password]" value="">
  </label>
  
  <input type="submit" name="" value="Sign Up">
</form>